# Basic
LEARNING_RATE_DEFAULT = 1e-3    # 0.001
MAX_EPOCHS_DEFAULT = 200
EVAL_FREQ_DEFAULT = 5
BATCH_SIZE_DEFAULT = 20
OPTIMIZER_DEFAULT = 'ADAM'
WEIGHT_DECAY_DEFAULT = 0.01
DATA_DIR_DEFAULT = 'data/ny2016_0101to0331/'
LOG_DEFAULT = 'log/'
WORKERS_DEFAULT = 4
USE_GPU_DEFAULT = 1
NETWORK_DEFAULT = 'Gallat'
MODE_DEFAULT = 'train'
EVAL_DEFAULT = 'eval'   # should be a model file name
